services:
  app:
   build: .
   volumes:
   - .:/django
   expose:
    - 8000
   env_file:
    - ./.env
   image: application:django
   container_name: app_container
   command: gunicorn cloudlearnbackend.wsgi:application --bind 0.0.0.0:8000
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app