# Generated by Django 4.2.5 on 2024-04-16 20:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, default='media/covers/default.jpg', null=True, upload_to=api.models.upload_path)),
            ],
        ),
    ]
