# Generated by Django 4.2.5 on 2024-05-24 21:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_section_subtopic_topic_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
