# Generated by Django 4.2.5 on 2024-06-01 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_section_cover_alter_subtopic_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
