# Generated by Django 4.2.5 on 2024-06-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_section_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='created_by',
        ),
    ]
