# Generated by Django 4.2.5 on 2024-07-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_section_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='username',
        ),
    ]
