# Generated by Django 4.2.5 on 2024-09-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_section_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_public',
        ),
    ]
