# Generated by Django 4.2.5 on 2024-09-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_section_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='flash_card',
            field=models.ManyToManyField(blank=True, related_name='flash_card', to='api.flashcard'),
        ),
    ]
