# Generated by Django 4.2.5 on 2024-09-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_flashcard_subtopic_flash_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='flash_card',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='subtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='api.subtopic'),
            preserve_default=False,
        ),
    ]
