# Generated by Django 4.2.5 on 2024-09-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_subtopic_flash_card_flashcard_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
