# Generated by Django 4.2.5 on 2024-10-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
